sudo: required

services: 
  - docker

before_install:
  - docker build -t michjop/testreact -f Dockerfile.dev .

script:
  - docker run michjop/testreact npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-083928633382"
  bucket_path: "docker-react"
  access_key_id: $AWS-ACCESS-KEY
  secret_access_key: 
    secure: "$AWS-SECRET-KEY"
  on:
    branch: master